#!/bin/sh

log() {
  [ "$logging" ] && printf 'debug: %s\n' "$@" >&2
}

if [ "$1" = --debug ]; then
  logging=true
fi

if [ "$1" != get ]; then
  log "Action not 'get', exiting"
  exit 0
fi

while read -r this_line; do
  log "Received: $this_line"
  case $this_line in
    host=*)
      pass_entry="$(case "${this_line#host=}" in
##CASES##
      esac)"
      if [ "$pass_entry" ]; then
        log "Pass entry found: $pass_entry"
        printf 'password=%s\n' "$(pass show "$pass_entry")"
      else
        log "Could not find a pass entry"
        return 1
      fi
      ;;
    *) log "Ignoring..."
  esac
done
