#!/bin/sh

log() {
  [ "$logging" ] && printf 'debug: %s\n' "$@" >&2
}

if [ "$1" = --debug ]; then
  logging=true
  shift
fi

if [ "$1" != get ]; then
  log "Action not 'get', exiting"
  exit 0
fi

while read -r this_line; do
  log "Received: $this_line"
  case $this_line in
    host=*)
      pass_entry="Git/${this_line#host=}"
      log "Using pass entry: $pass_entry"
      printf 'password=%s\n' "$(pass show "$pass_entry")"
      ;;
    *) log "Ignoring..."
  esac
done
